---
- name: Install mocp.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ mocp_apt_packages }}"

- name: Create moc config directory.
  file:
    path: "~/.moc"
    state: directory

- name: Copy moc config template.
  template:
    src: mocp-config.j2
    dest: "~/.moc/config"

- name: Include vim-like keybindings.
  include_vars: mocp-vim-like-keybindings.yml
  when: mocp_use_vim_keybindings

- name: Copy moc keymap template.
  template:
    src: mocp-keymap.j2
    dest: "~/.moc/keymap"

- include: scrobbler.yml
  when: mocp_configure_scrobbler
