---
- name: Install mocp.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ mocp_apt_packages }}"

- name: Create moc config directory.
  file:
    path: "~/.moc"
    state: directory

- name: Copy moc config template.
  template:
    src: mocp-config.j2
    dest: "~/.moc/config"
